import pytest
from tempfile import TemporaryDirectory
import lzma
from zipfile import ZipFile, ZIP_LZMA
import os
from gidpublish.utility.gidtools_functions import pathmaker, writeit, readit
from gidpublish.arma_tools.functions_hpp_handling import FunctionsHppFinder
from gidpublish.utility.named_tuples import ASFunctionItem


THIS_FILE_DIR = pathmaker(os.path.abspath(os.path.dirname(__file__)))
FAKE_ANSTISTASI_REPO_ZIPFILE = pathmaker(THIS_FILE_DIR, '../fake_antistasi_repo_archive.zip')


def find_functions_hpp(start_dir):
    for dirname, folderlist, filelist in os.walk(start_dir):
        if 'JeroenArsenal' not in dirname:
            for file in filelist:
                if file.casefold() == 'functions.hpp':
                    return pathmaker(dirname, file)


def find_functions_folder(start_dir):
    for dirname, folderlist, filelist in os.walk(start_dir):
        if 'JeroenArsenal' not in dirname:
            for folder in folderlist:
                if folder.casefold() == 'functions':
                    return pathmaker(dirname, folder)


@pytest.fixture()
def fake_arma_repo():
    with TemporaryDirectory() as tempdir:
        with ZipFile(FAKE_ANSTISTASI_REPO_ZIPFILE, 'r', compression=ZIP_LZMA) as zippy:
            for item in zippy.namelist():
                _info = zippy.getinfo(item)
                if _info.is_dir() is True:
                    os.makedirs(pathmaker(tempdir, item))
                else:
                    zippy.extract(item, pathmaker(tempdir))
        yield pathmaker(list(os.scandir(tempdir))[0].path)


@pytest.fixture()
def functions_finder(fake_arma_repo):
    functions_hpp = find_functions_hpp(fake_arma_repo)
    functions_folder = find_functions_folder(fake_arma_repo)
    func_finder = FunctionsHppFinder(functions_folder, functions_hpp)
    yield func_finder, fake_arma_repo


@pytest.fixture()
def function_finds():
    return {'AI': [ASFunctionItem(file_name='fn_airbomb.sqf', file_path='functions/AI/fn_airbomb.sqf', class_name='airbomb', function_name='A3A_fnc_airbomb'),
                   ASFunctionItem(file_name='fn_airdrop.sqf', file_path='functions/AI/fn_airdrop.sqf', class_name='airdrop', function_name='A3A_fnc_airdrop'),
                   ASFunctionItem(file_name='fn_AIreactOnKill.sqf', file_path='functions/AI/fn_AIreactOnKill.sqf', class_name='AIreactOnKill', function_name='A3A_fnc_AIreactOnKill'),
                   ASFunctionItem(file_name='fn_airstrike.sqf', file_path='functions/AI/fn_airstrike.sqf', class_name='airstrike', function_name='A3A_fnc_airstrike'),
                   ASFunctionItem(file_name='fn_artillery.sqf', file_path='functions/AI/fn_artillery.sqf', class_name='artillery', function_name='A3A_fnc_artillery'),
                   ASFunctionItem(file_name='fn_artySupport.sqf', file_path='functions/AI/fn_artySupport.sqf', class_name='artySupport', function_name='A3A_fnc_artySupport'),
                   ASFunctionItem(file_name='fn_askHelp.sqf', file_path='functions/AI/fn_askHelp.sqf', class_name='askHelp', function_name='A3A_fnc_askHelp'),
                   ASFunctionItem(file_name='fn_assaultBuilding.sqf', file_path='functions/AI/fn_assaultBuilding.sqf', class_name='assaultBuilding', function_name='A3A_fnc_assaultBuilding'),
                   ASFunctionItem(file_name='fn_attackDrillAI.sqf', file_path='functions/AI/fn_attackDrillAI.sqf', class_name='attackDrillAI', function_name='A3A_fnc_attackDrillAI'),
                   ASFunctionItem(file_name='fn_autoHealFnc.sqf', file_path='functions/AI/fn_autoHealFnc.sqf', class_name='autoHealFnc', function_name='A3A_fnc_autoHealFnc'),
                   ASFunctionItem(file_name='fn_autoLoot.sqf', file_path='functions/AI/fn_autoLoot.sqf', class_name='autoLoot', function_name='A3A_fnc_autoLoot'),
                   ASFunctionItem(file_name='fn_autoRearm.sqf', file_path='functions/AI/fn_autoRearm.sqf', class_name='autoRearm', function_name='A3A_fnc_autoRearm'),
                   ASFunctionItem(file_name='fn_canConquer.sqf', file_path='functions/AI/fn_canConquer.sqf', class_name='canConquer', function_name='A3A_fnc_canConquer'),
                   ASFunctionItem(file_name='fn_canFight.sqf', file_path='functions/AI/fn_canFight.sqf', class_name='canFight', function_name='A3A_fnc_canFight'),
                   ASFunctionItem(file_name='fn_captureX.sqf', file_path='functions/AI/fn_captureX.sqf', class_name='captureX', function_name='A3A_fnc_captureX'),
                   ASFunctionItem(file_name='fn_chargeWithSmoke.sqf', file_path='functions/AI/fn_chargeWithSmoke.sqf', class_name='chargeWithSmoke', function_name='A3A_fnc_chargeWithSmoke'),
                   ASFunctionItem(file_name='fn_coverage.sqf', file_path='functions/AI/fn_coverage.sqf', class_name='coverage', function_name='A3A_fnc_coverage'),
                   ASFunctionItem(file_name='fn_destroyBuilding.sqf', file_path='functions/AI/fn_destroyBuilding.sqf', class_name='destroyBuilding', function_name='A3A_fnc_destroyBuilding'),
                   ASFunctionItem(file_name='fn_doFlank.sqf', file_path='functions/AI/fn_doFlank.sqf', class_name='doFlank', function_name='A3A_fnc_doFlank'),
                   ASFunctionItem(file_name='fn_enemyList.sqf', file_path='functions/AI/fn_enemyList.sqf', class_name='enemyList', function_name='A3A_fnc_enemyList'),
                   ASFunctionItem(file_name='fn_entriesLand.sqf', file_path='functions/AI/fn_entriesLand.sqf', class_name='entriesLand', function_name='A3A_fnc_entriesLand'),
                   ASFunctionItem(file_name='fn_fastrope.sqf', file_path='functions/AI/fn_fastrope.sqf', class_name='fastrope', function_name='A3A_fnc_fastrope'),
                   ASFunctionItem(file_name='fn_findSafeRoadToUnload.sqf', file_path='functions/AI/fn_findSafeRoadToUnload.sqf', class_name='findSafeRoadToUnload', function_name='A3A_fnc_findSafeRoadToUnload'),
                   ASFunctionItem(file_name='fn_fleeToSide.sqf', file_path='functions/AI/fn_fleeToSide.sqf', class_name='fleeToSide', function_name='A3A_fnc_fleeToSide'),
                   ASFunctionItem(file_name='fn_guardDog.sqf', file_path='functions/AI/fn_guardDog.sqf', class_name='guardDog', function_name='A3A_fnc_guardDog'),
                   ASFunctionItem(file_name='fn_hasRadio.sqf', file_path='functions/AI/fn_hasRadio.sqf', class_name='hasRadio', function_name='A3A_fnc_hasRadio'),
                   ASFunctionItem(file_name='fn_help.sqf', file_path='functions/AI/fn_help.sqf', class_name='help', function_name='A3A_fnc_help'),
                   ASFunctionItem(file_name='fn_hideInBuilding.sqf', file_path='functions/AI/fn_hideInBuilding.sqf', class_name='hideInBuilding', function_name='A3A_fnc_hideInBuilding'),
                   ASFunctionItem(file_name='fn_inmuneConvoy.sqf', file_path='functions/AI/fn_inmuneConvoy.sqf', class_name='inmuneConvoy', function_name='A3A_fnc_inmuneConvoy'),
                   ASFunctionItem(file_name='fn_interrogate.sqf', file_path='functions/AI/fn_interrogate.sqf', class_name='interrogate', function_name='A3A_fnc_interrogate'),
                   ASFunctionItem(file_name='fn_isBuildingPosition.sqf', file_path='functions/AI/fn_isBuildingPosition.sqf', class_name='isBuildingPosition', function_name='A3A_fnc_isBuildingPosition'),
                   ASFunctionItem(file_name='fn_landThreatEval.sqf', file_path='functions/AI/fn_landThreatEval.sqf', class_name='landThreatEval', function_name='A3A_fnc_landThreatEval'),
                   ASFunctionItem(file_name='fn_liberatePOW.sqf', file_path='functions/AI/fn_liberatePOW.sqf', class_name='liberatePOW', function_name='A3A_fnc_liberatePOW'),
                   ASFunctionItem(file_name='fn_liberaterefugee.sqf', file_path='functions/AI/fn_liberaterefugee.sqf', class_name='liberaterefugee', function_name='A3A_fnc_liberaterefugee'),
                   ASFunctionItem(file_name='fn_mineSweep.sqf', file_path='functions/AI/fn_mineSweep.sqf', class_name='mineSweep', function_name='A3A_fnc_mineSweep'),
                   ASFunctionItem(file_name='fn_mortarDrill.sqf', file_path='functions/AI/fn_mortarDrill.sqf', class_name='mortarDrill', function_name='A3A_fnc_mortarDrill'),
                   ASFunctionItem(file_name='fn_mortarSupport.sqf', file_path='functions/AI/fn_mortarSupport.sqf', class_name='mortarSupport', function_name='A3A_fnc_mortarSupport'),
                   ASFunctionItem(file_name='fn_mortyAI.sqf', file_path='functions/AI/fn_mortyAI.sqf', class_name='mortyAI', function_name='A3A_fnc_mortyAI'),
                   ASFunctionItem(file_name='fn_napalm.sqf', file_path='functions/AI/fn_napalm.sqf', class_name='napalm', function_name='A3A_fnc_napalm'),
                   ASFunctionItem(file_name='fn_napalmDamage.sqf', file_path='functions/AI/fn_napalmDamage.sqf', class_name='napalmDamage', function_name='A3A_fnc_napalmDamage'),
                   ASFunctionItem(file_name='fn_nearEnemy.sqf', file_path='functions/AI/fn_nearEnemy.sqf', class_name='nearEnemy', function_name='A3A_fnc_nearEnemy'),
                   ASFunctionItem(file_name='fn_occupantInvaderUnitKilledEH.sqf', file_path='functions/AI/fn_occupantInvaderUnitKilledEH.sqf', class_name='occupantInvaderUnitKilledEH', function_name='A3A_fnc_occupantInvaderUnitKilledEH'),
                   ASFunctionItem(file_name='fn_rearmCall.sqf', file_path='functions/AI/fn_rearmCall.sqf', class_name='rearmCall', function_name='A3A_fnc_rearmCall'),
                   ASFunctionItem(file_name='fn_recallGroup.sqf', file_path='functions/AI/fn_recallGroup.sqf', class_name='recallGroup', function_name='A3A_fnc_recallGroup'),
                   ASFunctionItem(file_name='fn_smokeCoverAuto.sqf', file_path='functions/AI/fn_smokeCoverAuto.sqf', class_name='smokeCoverAuto', function_name='A3A_fnc_smokeCoverAuto'),
                   ASFunctionItem(file_name='fn_staticAutoT.sqf', file_path='functions/AI/fn_staticAutoT.sqf', class_name='staticAutoT', function_name='A3A_fnc_staticAutoT'),
                   ASFunctionItem(file_name='fn_staticMGDrill.sqf', file_path='functions/AI/fn_staticMGDrill.sqf', class_name='staticMGDrill', function_name='A3A_fnc_staticMGDrill'),
                   ASFunctionItem(file_name='fn_suppressingFire.sqf', file_path='functions/AI/fn_suppressingFire.sqf', class_name='suppressingFire', function_name='A3A_fnc_suppressingFire'),
                   ASFunctionItem(file_name='fn_surrenderAction.sqf', file_path='functions/AI/fn_surrenderAction.sqf', class_name='surrenderAction', function_name='A3A_fnc_surrenderAction'),
                   ASFunctionItem(file_name='fn_typeOfSoldier.sqf', file_path='functions/AI/fn_typeOfSoldier.sqf', class_name='typeOfSoldier', function_name='A3A_fnc_typeOfSoldier'),
                   ASFunctionItem(file_name='fn_undercoverAI.sqf', file_path='functions/AI/fn_undercoverAI.sqf', class_name='undercoverAI', function_name='A3A_fnc_undercoverAI'),
                   ASFunctionItem(file_name='fn_unitGetToCover.sqf', file_path='functions/AI/fn_unitGetToCover.sqf', class_name='unitGetToCover', function_name='A3A_fnc_unitGetToCover'),
                   ASFunctionItem(file_name='fn_useFlares.sqf', file_path='functions/AI/fn_useFlares.sqf', class_name='useFlares', function_name='A3A_fnc_useFlares'),
                   ASFunctionItem(file_name='fn_VANTinfo.sqf', file_path='functions/AI/fn_VANTinfo.sqf', class_name='VANTinfo', function_name='A3A_fnc_VANTinfo'),
                   ASFunctionItem(file_name='fn_vehicleMarkers.sqf', file_path='functions/AI/fn_vehicleMarkers.sqf', class_name='vehicleMarkers', function_name='A3A_fnc_vehicleMarkers')],
            'Ammunition': [ASFunctionItem(file_name='fn_ACEpvpReDress.sqf', file_path='functions/Ammunition/fn_ACEpvpReDress.sqf', class_name='ACEpvpReDress', function_name='A3A_fnc_ACEpvpReDress'),
                           ASFunctionItem(file_name='fn_ammunitionTransfer.sqf', file_path='functions/Ammunition/fn_ammunitionTransfer.sqf', class_name='ammunitionTransfer', function_name='A3A_fnc_ammunitionTransfer'),
                           ASFunctionItem(file_name='fn_arsenalManage.sqf', file_path='functions/Ammunition/fn_arsenalManage.sqf', class_name='arsenalManage', function_name='A3A_fnc_arsenalManage'),
                           ASFunctionItem(file_name='fn_categoryOverrides.sqf', file_path='functions/Ammunition/fn_categoryOverrides.sqf', class_name='categoryOverrides', function_name='A3A_fnc_categoryOverrides'),
                           ASFunctionItem(file_name='fn_checkRadiosUnlocked.sqf', file_path='functions/Ammunition/fn_checkRadiosUnlocked.sqf', class_name='checkRadiosUnlocked', function_name='A3A_fnc_checkRadiosUnlocked'),
                           ASFunctionItem(file_name='fn_configSort.sqf', file_path='functions/Ammunition/fn_configSort.sqf', class_name='configSort', function_name='A3A_fnc_configSort'),
                           ASFunctionItem(file_name='fn_crateLootParams.sqf', file_path='functions/Ammunition/fn_crateLootParams.sqf', class_name='crateLootParams', function_name='A3A_fnc_crateLootParams'),
                           ASFunctionItem(file_name='fn_dress.sqf', file_path='functions/Ammunition/fn_dress.sqf', class_name='dress', function_name='A3A_fnc_dress'),
                           ASFunctionItem(file_name='fn_empty.sqf', file_path='functions/Ammunition/fn_empty.sqf', class_name='empty', function_name='A3A_fnc_empty'),
                           ASFunctionItem(file_name='fn_equipmentClassToCategories.sqf', file_path='functions/Ammunition/fn_equipmentClassToCategories.sqf', class_name='equipmentClassToCategories', function_name='A3A_fnc_equipmentClassToCategories'),
                           ASFunctionItem(file_name='fn_equipmentIsValidForCurrentModset.sqf', file_path='functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf',
                                          class_name='equipmentIsValidForCurrentModset', function_name='A3A_fnc_equipmentIsValidForCurrentModset'),
                           ASFunctionItem(file_name='fn_equipmentSort.sqf', file_path='functions/Ammunition/fn_equipmentSort.sqf', class_name='equipmentSort', function_name='A3A_fnc_equipmentSort'),
                           ASFunctionItem(file_name='fn_fillLootCrate.sqf', file_path='functions/Ammunition/fn_fillLootCrate.sqf', class_name='fillLootCrate', function_name='A3A_fnc_fillLootCrate'),
                           ASFunctionItem(file_name='fn_getRadio.sqf', file_path='functions/Ammunition/fn_getRadio.sqf', class_name='getRadio', function_name='A3A_fnc_getRadio'),
                           ASFunctionItem(file_name='fn_itemSort.sqf', file_path='functions/Ammunition/fn_itemSort.sqf', class_name='itemSort', function_name='A3A_fnc_itemSort'),
                           ASFunctionItem(file_name='fn_itemType.sqf', file_path='functions/Ammunition/fn_itemType.sqf', class_name='itemType', function_name='A3A_fnc_itemType'),
                           ASFunctionItem(file_name='fn_launcherInfo.sqf', file_path='functions/Ammunition/fn_launcherInfo.sqf', class_name='launcherInfo', function_name='A3A_fnc_launcherInfo'),
                           ASFunctionItem(file_name='fn_loot.sqf', file_path='functions/Ammunition/fn_loot.sqf', class_name='loot', function_name='A3A_fnc_loot'),
                           ASFunctionItem(file_name='fn_randomRifle.sqf', file_path='functions/Ammunition/fn_randomRifle.sqf', class_name='randomRifle', function_name='A3A_fnc_randomRifle'),
                           ASFunctionItem(file_name='fn_transfer.sqf', file_path='functions/Ammunition/fn_transfer.sqf', class_name='transfer', function_name='A3A_fnc_transfer'),
                           ASFunctionItem(file_name='fn_unlockEquipment.sqf', file_path='functions/Ammunition/fn_unlockEquipment.sqf', class_name='unlockEquipment', function_name='A3A_fnc_unlockEquipment'),
                           ASFunctionItem(file_name='fn_vehicleSort.sqf', file_path='functions/Ammunition/fn_vehicleSort.sqf', class_name='vehicleSort', function_name='A3A_fnc_vehicleSort')],
            'Base': [ASFunctionItem(file_name='defineCommon.inc', file_path='functions/Base/defineCommon.inc', class_name='defineCommon', function_name='A3A_fnc_defineCommon'),
                     ASFunctionItem(file_name='fn_addActionBreachVehicle.sqf', file_path='functions/Base/fn_addActionBreachVehicle.sqf', class_name='addActionBreachVehicle', function_name='A3A_fnc_addActionBreachVehicle'),
                     ASFunctionItem(file_name='fn_addHC.sqf', file_path='functions/Base/fn_addHC.sqf', class_name='addHC', function_name='A3A_fnc_addHC'),
                     ASFunctionItem(file_name='fn_addTimeForIdle.sqf', file_path='functions/Base/fn_addTimeForIdle.sqf', class_name='addTimeForIdle', function_name='A3A_fnc_addTimeForIdle'),
                     ASFunctionItem(file_name='fn_aggressionUpdateLoop.sqf', file_path='functions/Base/fn_aggressionUpdateLoop.sqf', class_name='aggressionUpdateLoop', function_name='A3A_fnc_aggressionUpdateLoop'),
                     ASFunctionItem(file_name='fn_AILoadInfo.sqf', file_path='functions/Base/fn_AILoadInfo.sqf', class_name='AILoadInfo', function_name='A3A_fnc_AILoadInfo'),
                     ASFunctionItem(file_name='fn_blackout.sqf', file_path='functions/Base/fn_blackout.sqf', class_name='blackout', function_name='A3A_fnc_blackout'),
                     ASFunctionItem(file_name='fn_buildHQ.sqf', file_path='functions/Base/fn_buildHQ.sqf', class_name='buildHQ', function_name='A3A_fnc_buildHQ'),
                     ASFunctionItem(file_name='fn_calculateAggression.sqf', file_path='functions/Base/fn_calculateAggression.sqf', class_name='calculateAggression', function_name='A3A_fnc_calculateAggression'),
                     ASFunctionItem(file_name='fn_citiesToCivPatrol.sqf', file_path='functions/Base/fn_citiesToCivPatrol.sqf', class_name='citiesToCivPatrol', function_name='A3A_fnc_citiesToCivPatrol'),
                     ASFunctionItem(file_name='fn_citySupportChange.sqf', file_path='functions/Base/fn_citySupportChange.sqf', class_name='citySupportChange', function_name='A3A_fnc_citySupportChange'),
                     ASFunctionItem(file_name='fn_commsMP.sqf', file_path='functions/Base/fn_commsMP.sqf', class_name='commsMP', function_name='A3A_fnc_commsMP'),
                     ASFunctionItem(file_name='fn_createBreachChargeText.sqf', file_path='functions/Base/fn_createBreachChargeText.sqf', class_name='createBreachChargeText', function_name='A3A_fnc_createBreachChargeText'),
                     ASFunctionItem(file_name='fn_createControls.sqf', file_path='functions/Base/fn_createControls.sqf', class_name='createControls', function_name='A3A_fnc_createControls'),
                     ASFunctionItem(file_name='fn_createOutpostsFIA.sqf', file_path='functions/Base/fn_createOutpostsFIA.sqf', class_name='createOutpostsFIA', function_name='A3A_fnc_createOutpostsFIA'),
                     ASFunctionItem(file_name='fn_createPetros.sqf', file_path='functions/Base/fn_createPetros.sqf', class_name='createPetros', function_name='A3A_fnc_createPetros'),
                     ASFunctionItem(file_name='fn_deleteControls.sqf', file_path='functions/Base/fn_deleteControls.sqf', class_name='deleteControls', function_name='A3A_fnc_deleteControls'),
                     ASFunctionItem(file_name='fn_destroyCity.sqf', file_path='functions/Base/fn_destroyCity.sqf', class_name='destroyCity', function_name='A3A_fnc_destroyCity'),
                     ASFunctionItem(file_name='fn_distance.sqf', file_path='functions/Base/fn_distance.sqf', class_name='distance', function_name='A3A_fnc_distance'),
                     ASFunctionItem(file_name='fn_distanceUnits.sqf', file_path='functions/Base/fn_distanceUnits.sqf', class_name='distanceUnits', function_name='A3A_fnc_distanceUnits'),
                     ASFunctionItem(file_name='fn_economicsAI.sqf', file_path='functions/Base/fn_economicsAI.sqf', class_name='economicsAI', function_name='A3A_fnc_economicsAI'),
                     ASFunctionItem(file_name='fn_ejectPvPPlayerIfInvalidVehicle.sqf', file_path='functions/Base/fn_ejectPvPPlayerIfInvalidVehicle.sqf',
                                    class_name='ejectPvPPlayerIfInvalidVehicle', function_name='A3A_fnc_ejectPvPPlayerIfInvalidVehicle'),
                     ASFunctionItem(file_name='fn_FIAradio.sqf', file_path='functions/Base/fn_FIAradio.sqf', class_name='FIAradio', function_name='A3A_fnc_FIAradio'),
                     ASFunctionItem(file_name='fn_findBasesForConvoy.sqf', file_path='functions/Base/fn_findBasesForConvoy.sqf', class_name='findBasesForConvoy', function_name='A3A_fnc_findBasesForConvoy'),
                     ASFunctionItem(file_name='fn_findNearestGoodRoad.sqf', file_path='functions/Base/fn_findNearestGoodRoad.sqf', class_name='findNearestGoodRoad', function_name='A3A_fnc_findNearestGoodRoad'),
                     ASFunctionItem(file_name='fn_flagaction.sqf', file_path='functions/Base/fn_flagaction.sqf', class_name='flagaction', function_name='A3A_fnc_flagaction'),
                     ASFunctionItem(file_name='fn_fogCheck.sqf', file_path='functions/Base/fn_fogCheck.sqf', class_name='fogCheck', function_name='A3A_fnc_fogCheck'),
                     ASFunctionItem(file_name='fn_garbageCleaner.sqf', file_path='functions/Base/fn_garbageCleaner.sqf', class_name='garbageCleaner', function_name='A3A_fnc_garbageCleaner'),
                     ASFunctionItem(file_name='fn_garrisonInfo.sqf', file_path='functions/Base/fn_garrisonInfo.sqf', class_name='garrisonInfo', function_name='A3A_fnc_garrisonInfo'),
                     ASFunctionItem(file_name='fn_getAggroLevelString.sqf', file_path='functions/Base/fn_getAggroLevelString.sqf', class_name='getAggroLevelString', function_name='A3A_fnc_getAggroLevelString'),
                     ASFunctionItem(file_name='fn_getSideRadioTowerInfluence.sqf', file_path='functions/Base/fn_getSideRadioTowerInfluence.sqf', class_name='getSideRadioTowerInfluence', function_name='A3A_fnc_getSideRadioTowerInfluence'),
                     ASFunctionItem(file_name='fn_getVehiclePoolForAttacks.sqf', file_path='functions/Base/fn_getVehiclePoolForAttacks.sqf', class_name='getVehiclePoolForAttacks', function_name='A3A_fnc_getVehiclePoolForAttacks'),
                     ASFunctionItem(file_name='fn_getVehiclePoolForQRFs.sqf', file_path='functions/Base/fn_getVehiclePoolForQRFs.sqf', class_name='getVehiclePoolForQRFs', function_name='A3A_fnc_getVehiclePoolForQRFs'),
                     ASFunctionItem(file_name='fn_healAndRepair.sqf', file_path='functions/Base/fn_healAndRepair.sqf', class_name='healAndRepair', function_name='A3A_fnc_healAndRepair'),
                     ASFunctionItem(file_name='fn_initPetros.sqf', file_path='functions/Base/fn_initPetros.sqf', class_name='initPetros', function_name='A3A_fnc_initPetros'),
                     ASFunctionItem(file_name='fn_isFrontline.sqf', file_path='functions/Base/fn_isFrontline.sqf', class_name='isFrontline', function_name='A3A_fnc_isFrontline'),
                     ASFunctionItem(file_name='fn_isTheSameIsland.sqf', file_path='functions/Base/fn_isTheSameIsland.sqf', class_name='isTheSameIsland', function_name='A3A_fnc_isTheSameIsland'),
                     ASFunctionItem(file_name='fn_joinMultipleGroups.sqf', file_path='functions/Base/fn_joinMultipleGroups.sqf', class_name='joinMultipleGroups', function_name='A3A_fnc_joinMultipleGroups'),
                     ASFunctionItem(file_name='fn_keys.sqf', file_path='functions/Base/fn_keys.sqf', class_name='keys', function_name='A3A_fnc_keys'),
                     ASFunctionItem(file_name='fn_localizar.sqf', file_path='functions/Base/fn_localizar.sqf', class_name='localizar', function_name='A3A_fnc_localizar'),
                     ASFunctionItem(file_name='fn_location.sqf', file_path='functions/Base/fn_location.sqf', class_name='location', function_name='A3A_fnc_location'),
                     ASFunctionItem(file_name='fn_logPerformance.sqf', file_path='functions/Base/fn_logPerformance.sqf', class_name='logPerformance', function_name='A3A_fnc_logPerformance'),
                     ASFunctionItem(file_name='fn_markerChange.sqf', file_path='functions/Base/fn_markerChange.sqf', class_name='markerChange', function_name='A3A_fnc_markerChange'),
                     ASFunctionItem(file_name='fn_moveHQ.sqf', file_path='functions/Base/fn_moveHQ.sqf', class_name='moveHQ', function_name='A3A_fnc_moveHQ'),
                     ASFunctionItem(file_name='fn_mrkUpdate.sqf', file_path='functions/Base/fn_mrkUpdate.sqf', class_name='mrkUpdate', function_name='A3A_fnc_mrkUpdate'),
                     ASFunctionItem(file_name='fn_mrkWIN.sqf', file_path='functions/Base/fn_mrkWIN.sqf', class_name='mrkWIN', function_name='A3A_fnc_mrkWIN'),
                     ASFunctionItem(file_name='fn_NATOFT.sqf', file_path='functions/Base/fn_NATOFT.sqf', class_name='NATOFT', function_name='A3A_fnc_NATOFT'),
                     ASFunctionItem(file_name='fn_numericRank.sqf', file_path='functions/Base/fn_numericRank.sqf', class_name='numericRank', function_name='A3A_fnc_numericRank'),
                     ASFunctionItem(file_name='fn_onHeadlessClientDisconnect.sqf', file_path='functions/Base/fn_onHeadlessClientDisconnect.sqf', class_name='onHeadlessClientDisconnect', function_name='A3A_fnc_onHeadlessClientDisconnect'),
                     ASFunctionItem(file_name='fn_onPlayerDisconnect.sqf', file_path='functions/Base/fn_onPlayerDisconnect.sqf', class_name='onPlayerDisconnect', function_name='A3A_fnc_onPlayerDisconnect'),
                     ASFunctionItem(file_name='fn_outpostDialog.sqf', file_path='functions/Base/fn_outpostDialog.sqf', class_name='outpostDialog', function_name='A3A_fnc_outpostDialog'),
                     ASFunctionItem(file_name='fn_patrolDestinations.sqf', file_path='functions/Base/fn_patrolDestinations.sqf', class_name='patrolDestinations', function_name='A3A_fnc_patrolDestinations'),
                     ASFunctionItem(file_name='fn_placementselection.sqf', file_path='functions/Base/fn_placementselection.sqf', class_name='placementselection', function_name='A3A_fnc_placementselection'),
                     ASFunctionItem(file_name='fn_playableUnits.sqf', file_path='functions/Base/fn_playableUnits.sqf', class_name='playableUnits', function_name='A3A_fnc_playableUnits'),
                     ASFunctionItem(file_name='fn_powerReorg.sqf', file_path='functions/Base/fn_powerReorg.sqf', class_name='powerReorg', function_name='A3A_fnc_powerReorg'),
                     ASFunctionItem(file_name='fn_prestige.sqf', file_path='functions/Base/fn_prestige.sqf', class_name='prestige', function_name='A3A_fnc_prestige'),
                     ASFunctionItem(file_name='fn_radioCheck.sqf', file_path='functions/Base/fn_radioCheck.sqf', class_name='radioCheck', function_name='A3A_fnc_radioCheck'),
                     ASFunctionItem(file_name='fn_rebelAttack.sqf', file_path='functions/Base/fn_rebelAttack.sqf', class_name='rebelAttack', function_name='A3A_fnc_rebelAttack'),
                     ASFunctionItem(file_name='fn_rebuildAssets.sqf', file_path='functions/Base/fn_rebuildAssets.sqf', class_name='rebuildAssets', function_name='A3A_fnc_rebuildAssets'),
                     ASFunctionItem(file_name='fn_rebuildRadioTower.sqf', file_path='functions/Base/fn_rebuildRadioTower.sqf', class_name='rebuildRadioTower', function_name='A3A_fnc_rebuildRadioTower'),
                     ASFunctionItem(file_name='fn_relocateHQObjects.sqf', file_path='functions/Base/fn_relocateHQObjects.sqf', class_name='relocateHQObjects', function_name='A3A_fnc_relocateHQObjects'),
                     ASFunctionItem(file_name='fn_remUnitCount.sqf', file_path='functions/Base/fn_remUnitCount.sqf', class_name='remUnitCount', function_name='A3A_fnc_remUnitCount'),
                     ASFunctionItem(file_name='fn_repairRuinedBuilding.sqf', file_path='functions/Base/fn_repairRuinedBuilding.sqf', class_name='repairRuinedBuilding', function_name='A3A_fnc_repairRuinedBuilding'),
                     ASFunctionItem(file_name='fn_resourcecheckSkipTime.sqf', file_path='functions/Base/fn_resourcecheckSkipTime.sqf', class_name='resourcecheckSkipTime', function_name='A3A_fnc_resourcecheckSkipTime'),
                     ASFunctionItem(file_name='fn_resourcesFIA.sqf', file_path='functions/Base/fn_resourcesFIA.sqf', class_name='resourcesFIA', function_name='A3A_fnc_resourcesFIA'),
                     ASFunctionItem(file_name='fn_returnMuzzle.sqf', file_path='functions/Base/fn_returnMuzzle.sqf', class_name='returnMuzzle', function_name='A3A_fnc_returnMuzzle'),
                     ASFunctionItem(file_name='fn_revealToPlayer.sqf', file_path='functions/Base/fn_revealToPlayer.sqf', class_name='revealToPlayer', function_name='A3A_fnc_revealToPlayer'),
                     ASFunctionItem(file_name='fn_scheduler.sqf', file_path='functions/Base/fn_scheduler.sqf', class_name='scheduler', function_name='A3A_fnc_scheduler'),
                     ASFunctionItem(file_name='fn_sellVehicle.sqf', file_path='functions/Base/fn_sellVehicle.sqf', class_name='sellVehicle', function_name='A3A_fnc_sellVehicle'),
                     ASFunctionItem(file_name='fn_setMarkerAlphaForSide.sqf', file_path='functions/Base/fn_setMarkerAlphaForSide.sqf', class_name='setMarkerAlphaForSide', function_name='A3A_fnc_setMarkerAlphaForSide'),
                     ASFunctionItem(file_name='fn_singlePlayerBlackScreenWarning.sqf', file_path='functions/Base/fn_singlePlayerBlackScreenWarning.sqf',
                                    class_name='singlePlayerBlackScreenWarning', function_name='A3A_fnc_singlePlayerBlackScreenWarning'),
                     ASFunctionItem(file_name='fn_sizeMarker.sqf', file_path='functions/Base/fn_sizeMarker.sqf', class_name='sizeMarker', function_name='A3A_fnc_sizeMarker'),
                     ASFunctionItem(file_name='fn_splitVehicleCrewIntoOwnGroups.sqf', file_path='functions/Base/fn_splitVehicleCrewIntoOwnGroups.sqf', class_name='splitVehicleCrewIntoOwnGroups', function_name='A3A_fnc_splitVehicleCrewIntoOwnGroups'),
                     ASFunctionItem(file_name='fn_startBreachVehicle.sqf', file_path='functions/Base/fn_startBreachVehicle.sqf', class_name='startBreachVehicle', function_name='A3A_fnc_startBreachVehicle'),
                     ASFunctionItem(file_name='fn_startTestingTimer.sqf', file_path='functions/Base/fn_startTestingTimer.sqf', class_name='startTestingTimer', function_name='A3A_fnc_startTestingTimer'),
                     ASFunctionItem(file_name='fn_statistics.sqf', file_path='functions/Base/fn_statistics.sqf', class_name='statistics', function_name='A3A_fnc_statistics'),
                     ASFunctionItem(file_name='fn_stripGearFromLoadout.sqf', file_path='functions/Base/fn_stripGearFromLoadout.sqf', class_name='stripGearFromLoadout', function_name='A3A_fnc_stripGearFromLoadout'),
                     ASFunctionItem(file_name='fn_teleportVehicleToBase.sqf', file_path='functions/Base/fn_teleportVehicleToBase.sqf', class_name='teleportVehicleToBase', function_name='A3A_fnc_teleportVehicleToBase'),
                     ASFunctionItem(file_name='fn_timingCA.sqf', file_path='functions/Base/fn_timingCA.sqf', class_name='timingCA', function_name='A3A_fnc_timingCA'),
                     ASFunctionItem(file_name='fn_translateVariable.sqf', file_path='functions/Base/fn_translateVariable.sqf', class_name='translateVariable', function_name='A3A_fnc_translateVariable'),
                     ASFunctionItem(file_name='fn_unlockVehicle.sqf', file_path='functions/Base/fn_unlockVehicle.sqf', class_name='unlockVehicle', function_name='A3A_fnc_unlockVehicle'),
                     ASFunctionItem(file_name='fn_zoneCheck.sqf', file_path='functions/Base/fn_zoneCheck.sqf', class_name='zoneCheck', function_name='A3A_fnc_zoneCheck')],
            'CREATE': [ASFunctionItem(file_name='fn_AAFroadPatrol.sqf', file_path='functions/CREATE/fn_AAFroadPatrol.sqf', class_name='AAFroadPatrol', function_name='A3A_fnc_AAFroadPatrol'),
                       ASFunctionItem(file_name='fn_airportCanAttack.sqf', file_path='functions/CREATE/fn_airportCanAttack.sqf', class_name='airportCanAttack', function_name='A3A_fnc_airportCanAttack'),
                       ASFunctionItem(file_name='fn_AIVEHinit.sqf', file_path='functions/CREATE/fn_AIVEHinit.sqf', class_name='AIVEHinit', function_name='A3A_fnc_AIVEHinit'),
                       ASFunctionItem(file_name='fn_ambientCivs.sqf', file_path='functions/CREATE/fn_ambientCivs.sqf', class_name='ambientCivs', function_name='A3A_fnc_ambientCivs'),
                       ASFunctionItem(file_name='fn_calculateMarkerArea.sqf', file_path='functions/CREATE/fn_calculateMarkerArea.sqf', class_name='calculateMarkerArea', function_name='A3A_fnc_calculateMarkerArea'),
                       ASFunctionItem(file_name='fn_cargoSeats.sqf', file_path='functions/CREATE/fn_cargoSeats.sqf', class_name='cargoSeats', function_name='A3A_fnc_cargoSeats'),
                       ASFunctionItem(file_name='fn_CIVinit.sqf', file_path='functions/CREATE/fn_CIVinit.sqf', class_name='CIVinit', function_name='A3A_fnc_CIVinit'),
                       ASFunctionItem(file_name='fn_civVEHinit.sqf', file_path='functions/CREATE/fn_civVEHinit.sqf', class_name='civVEHinit', function_name='A3A_fnc_civVEHinit'),
                       ASFunctionItem(file_name='fn_cleanserVeh.sqf', file_path='functions/CREATE/fn_cleanserVeh.sqf', class_name='cleanserVeh', function_name='A3A_fnc_cleanserVeh'),
                       ASFunctionItem(file_name='fn_createAIAirplane.sqf', file_path='functions/CREATE/fn_createAIAirplane.sqf', class_name='createAIAirplane', function_name='A3A_fnc_createAIAirplane'),
                       ASFunctionItem(file_name='fn_createAICities.sqf', file_path='functions/CREATE/fn_createAICities.sqf', class_name='createAICities', function_name='A3A_fnc_createAICities'),
                       ASFunctionItem(file_name='fn_createAIcontrols.sqf', file_path='functions/CREATE/fn_createAIcontrols.sqf', class_name='createAIcontrols', function_name='A3A_fnc_createAIcontrols'),
                       ASFunctionItem(file_name='fn_createAIOutposts.sqf', file_path='functions/CREATE/fn_createAIOutposts.sqf', class_name='createAIOutposts', function_name='A3A_fnc_createAIOutposts'),
                       ASFunctionItem(file_name='fn_createAIResources.sqf', file_path='functions/CREATE/fn_createAIResources.sqf', class_name='createAIResources', function_name='A3A_fnc_createAIResources'),
                       ASFunctionItem(file_name='fn_createAISite.sqf', file_path='functions/CREATE/fn_createAISite.sqf', class_name='createAISite', function_name='A3A_fnc_createAISite'),
                       ASFunctionItem(file_name='fn_createCIV.sqf', file_path='functions/CREATE/fn_createCIV.sqf', class_name='createCIV', function_name='A3A_fnc_createCIV'),
                       ASFunctionItem(file_name='fn_createFIAOutposts2.sqf', file_path='functions/CREATE/fn_createFIAOutposts2.sqf', class_name='createFIAOutposts2', function_name='A3A_fnc_createFIAOutposts2'),
                       ASFunctionItem(file_name='fn_createQRF.sqf', file_path='functions/CREATE/fn_createQRF.sqf', class_name='createQRF', function_name='A3A_fnc_createQRF'),
                       ASFunctionItem(file_name='fn_createSDKgarrisons.sqf', file_path='functions/CREATE/fn_createSDKgarrisons.sqf', class_name='createSDKgarrisons', function_name='A3A_fnc_createSDKgarrisons'),
                       ASFunctionItem(file_name='fn_createSDKgarrisonsTemp.sqf', file_path='functions/CREATE/fn_createSDKgarrisonsTemp.sqf', class_name='createSDKgarrisonsTemp', function_name='A3A_fnc_createSDKgarrisonsTemp'),
                       ASFunctionItem(file_name='fn_createUnit.sqf', file_path='functions/CREATE/fn_createUnit.sqf', class_name='createUnit', function_name='A3A_fnc_createUnit'),
                       ASFunctionItem(file_name='fn_cycleSpawn.sqf', file_path='functions/CREATE/fn_cycleSpawn.sqf', class_name='cycleSpawn', function_name='A3A_fnc_cycleSpawn'),
                       ASFunctionItem(file_name='fn_FIAinitBASES.sqf', file_path='functions/CREATE/fn_FIAinitBASES.sqf', class_name='FIAinitBASES', function_name='A3A_fnc_FIAinitBASES'),
                       ASFunctionItem(file_name='fn_findSpawnPosition.sqf', file_path='functions/CREATE/fn_findSpawnPosition.sqf', class_name='findSpawnPosition', function_name='A3A_fnc_findSpawnPosition'),
                       ASFunctionItem(file_name='fn_freeSpawnPositions.sqf', file_path='functions/CREATE/fn_freeSpawnPositions.sqf', class_name='freeSpawnPositions', function_name='A3A_fnc_freeSpawnPositions'),
                       ASFunctionItem(file_name='fn_garrisonReorg.sqf', file_path='functions/CREATE/fn_garrisonReorg.sqf', class_name='garrisonReorg', function_name='A3A_fnc_garrisonReorg'),
                       ASFunctionItem(file_name='fn_garrisonSize.sqf', file_path='functions/CREATE/fn_garrisonSize.sqf', class_name='garrisonSize', function_name='A3A_fnc_garrisonSize'),
                       ASFunctionItem(file_name='fn_garrisonUpdate.sqf', file_path='functions/CREATE/fn_garrisonUpdate.sqf', class_name='garrisonUpdate', function_name='A3A_fnc_garrisonUpdate'),
                       ASFunctionItem(file_name='fn_groupDespawner.sqf', file_path='functions/CREATE/fn_groupDespawner.sqf', class_name='groupDespawner', function_name='A3A_fnc_groupDespawner'),
                       ASFunctionItem(file_name='fn_invaderPunish.sqf', file_path='functions/CREATE/fn_invaderPunish.sqf', class_name='invaderPunish', function_name='A3A_fnc_invaderPunish'),
                       ASFunctionItem(file_name='fn_milBuildings.sqf', file_path='functions/CREATE/fn_milBuildings.sqf', class_name='milBuildings', function_name='A3A_fnc_milBuildings'),
                       ASFunctionItem(file_name='fn_minefieldAAF.sqf', file_path='functions/CREATE/fn_minefieldAAF.sqf', class_name='minefieldAAF', function_name='A3A_fnc_minefieldAAF'),
                       ASFunctionItem(file_name='fn_mortarPos.sqf', file_path='functions/CREATE/fn_mortarPos.sqf', class_name='mortarPos', function_name='A3A_fnc_mortarPos'),
                       ASFunctionItem(file_name='fn_NATOinit.sqf', file_path='functions/CREATE/fn_NATOinit.sqf', class_name='NATOinit', function_name='A3A_fnc_NATOinit'),
                       ASFunctionItem(file_name='fn_patrolCA.sqf', file_path='functions/CREATE/fn_patrolCA.sqf', class_name='patrolCA', function_name='A3A_fnc_patrolCA'),
                       ASFunctionItem(file_name='fn_patrolReinf.sqf', file_path='functions/CREATE/fn_patrolReinf.sqf', class_name='patrolReinf', function_name='A3A_fnc_patrolReinf'),
                       ASFunctionItem(file_name='fn_reinforcementsAI.sqf', file_path='functions/CREATE/fn_reinforcementsAI.sqf', class_name='reinforcementsAI', function_name='A3A_fnc_reinforcementsAI'),
                       ASFunctionItem(file_name='fn_remoteBattle.sqf', file_path='functions/CREATE/fn_remoteBattle.sqf', class_name='remoteBattle', function_name='A3A_fnc_remoteBattle'),
                       ASFunctionItem(file_name='fn_removeVehFromPool.sqf', file_path='functions/CREATE/fn_removeVehFromPool.sqf', class_name='removeVehFromPool', function_name='A3A_fnc_removeVehFromPool'),
                       ASFunctionItem(file_name='fn_safeVehicleSpawn.sqf', file_path='functions/CREATE/fn_safeVehicleSpawn.sqf', class_name='safeVehicleSpawn', function_name='A3A_fnc_safeVehicleSpawn'),
                       ASFunctionItem(file_name='fn_spawnGroup.sqf', file_path='functions/CREATE/fn_spawnGroup.sqf', class_name='spawnGroup', function_name='A3A_fnc_spawnGroup'),
                       ASFunctionItem(file_name='fn_updateCAMark.sqf', file_path='functions/CREATE/fn_updateCAMark.sqf', class_name='updateCAMark', function_name='A3A_fnc_updateCAMark'),
                       ASFunctionItem(file_name='fn_vehAvailable.sqf', file_path='functions/CREATE/fn_vehAvailable.sqf', class_name='vehAvailable', function_name='A3A_fnc_vehAvailable'),
                       ASFunctionItem(file_name='fn_VEHdespawner.sqf', file_path='functions/CREATE/fn_VEHdespawner.sqf', class_name='VEHdespawner', function_name='A3A_fnc_VEHdespawner'),
                       ASFunctionItem(file_name='fn_vehKilledOrCaptured.sqf', file_path='functions/CREATE/fn_vehKilledOrCaptured.sqf', class_name='vehKilledOrCaptured', function_name='A3A_fnc_vehKilledOrCaptured'),
                       ASFunctionItem(file_name='fn_wavedCA.sqf', file_path='functions/CREATE/fn_wavedCA.sqf', class_name='wavedCA', function_name='A3A_fnc_wavedCA'),
                       ASFunctionItem(file_name='fn_WPCreate.sqf', file_path='functions/CREATE/fn_WPCreate.sqf', class_name='WPCreate', function_name='A3A_fnc_WPCreate')],
            'Convoy': [ASFunctionItem(file_name='fn_cleanConvoyMarker.sqf', file_path='functions/Convoy/fn_cleanConvoyMarker.sqf', class_name='cleanConvoyMarker', function_name='A3A_fnc_cleanConvoyMarker'),
                       ASFunctionItem(file_name='fn_convoyDebug.sqf', file_path='functions/Convoy/fn_convoyDebug.sqf', class_name='convoyDebug', function_name='A3A_fnc_convoyDebug'),
                       ASFunctionItem(file_name='fn_convoyMovement.sqf', file_path='functions/Convoy/fn_convoyMovement.sqf', class_name='convoyMovement', function_name='A3A_fnc_convoyMovement'),
                       ASFunctionItem(file_name='fn_createAIAction.sqf', file_path='functions/Convoy/fn_createAIAction.sqf', class_name='createAIAction', function_name='A3A_fnc_createAIAction'),
                       ASFunctionItem(file_name='fn_createConvoy.sqf', file_path='functions/Convoy/fn_createConvoy.sqf', class_name='createConvoy', function_name='A3A_fnc_createConvoy'),
                       ASFunctionItem(file_name='fn_despawnConvoy.sqf', file_path='functions/Convoy/fn_despawnConvoy.sqf', class_name='despawnConvoy', function_name='A3A_fnc_despawnConvoy'),
                       ASFunctionItem(file_name='fn_findAirportForAirstrike.sqf', file_path='functions/Convoy/fn_findAirportForAirstrike.sqf', class_name='findAirportForAirstrike', function_name='A3A_fnc_findAirportForAirstrike'),
                       ASFunctionItem(file_name='fn_followVehicle.sqf', file_path='functions/Convoy/fn_followVehicle.sqf', class_name='followVehicle', function_name='A3A_fnc_followVehicle'),
                       ASFunctionItem(file_name='fn_onConvoyArrival.sqf', file_path='functions/Convoy/fn_onConvoyArrival.sqf', class_name='onConvoyArrival', function_name='A3A_fnc_onConvoyArrival'),
                       ASFunctionItem(file_name='fn_roadblockFight.sqf', file_path='functions/Convoy/fn_roadblockFight.sqf', class_name='roadblockFight', function_name='A3A_fnc_roadblockFight'),
                       ASFunctionItem(file_name='fn_selectAndCreateVehicle.sqf', file_path='functions/Convoy/fn_selectAndCreateVehicle.sqf', class_name='selectAndCreateVehicle', function_name='A3A_fnc_selectAndCreateVehicle'),
                       ASFunctionItem(file_name='fn_spawnConvoy.sqf', file_path='functions/Convoy/fn_spawnConvoy.sqf', class_name='spawnConvoy', function_name='A3A_fnc_spawnConvoy'),
                       ASFunctionItem(file_name='fn_spawnConvoyLine.sqf', file_path='functions/Convoy/fn_spawnConvoyLine.sqf', class_name='spawnConvoyLine', function_name='A3A_fnc_spawnConvoyLine'),
                       ASFunctionItem(file_name='getUnitWeaponData.sqf', file_path='functions/Convoy/getUnitWeaponData.sqf', class_name='getUnitWeaponData', function_name='A3A_fnc_getUnitWeaponData'),
                       ASFunctionItem(file_name='PrepareFightData.sqf', file_path='functions/Convoy/PrepareFightData.sqf', class_name='PrepareFightData', function_name='A3A_fnc_PrepareFightData')],
            'Debugging': [ASFunctionItem(file_name='fn_deleteEmptyGroupsOnSide.sqf', file_path='functions/Debugging/fn_deleteEmptyGroupsOnSide.sqf', class_name='deleteEmptyGroupsOnSide', function_name='A3A_fnc_deleteEmptyGroupsOnSide'),
                          ASFunctionItem(file_name='fn_installSchrodingersBuildingFix.sqf', file_path='functions/Debugging/fn_installSchrodingersBuildingFix.sqf',
                                         class_name='installSchrodingersBuildingFix', function_name='A3A_fnc_installSchrodingersBuildingFix'),
                          ASFunctionItem(file_name='fn_spawnDebuggingLoop.sqf', file_path='functions/Debugging/fn_spawnDebuggingLoop.sqf', class_name='spawnDebuggingLoop', function_name='A3A_fnc_spawnDebuggingLoop')],
            'Dialogs': [ASFunctionItem(file_name='fn_buyVehicle.sqf', file_path='functions/Dialogs/fn_buyVehicle.sqf', class_name='buyVehicle', function_name='A3A_fnc_buyVehicle'),
                        ASFunctionItem(file_name='fn_buyVehicleCiv.sqf', file_path='functions/Dialogs/fn_buyVehicleCiv.sqf', class_name='buyVehicleCiv', function_name='A3A_fnc_buyVehicleCiv'),
                        ASFunctionItem(file_name='fn_clearForest.sqf', file_path='functions/Dialogs/fn_clearForest.sqf', class_name='clearForest', function_name='A3A_fnc_clearForest'),
                        ASFunctionItem(file_name='fn_createDialog_setParams.sqf', file_path='functions/Dialogs/fn_createDialog_setParams.sqf', class_name='createDialog_setParams', function_name='A3A_fnc_createDialog_setParams'),
                        ASFunctionItem(file_name='fn_createDialog_shouldLoadPersonalSave.sqf', file_path='functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf',
                                       class_name='createDialog_shouldLoadPersonalSave', function_name='A3A_fnc_createDialog_shouldLoadPersonalSave'),
                        ASFunctionItem(file_name='fn_dialogHQ.sqf', file_path='functions/Dialogs/fn_dialogHQ.sqf', class_name='dialogHQ', function_name='A3A_fnc_dialogHQ'),
                        ASFunctionItem(file_name='fn_fastTravelRadio.sqf', file_path='functions/Dialogs/fn_fastTravelRadio.sqf', class_name='fastTravelRadio', function_name='A3A_fnc_fastTravelRadio'),
                        ASFunctionItem(file_name='fn_loadPreviousSession.sqf', file_path='functions/Dialogs/fn_loadPreviousSession.sqf', class_name='loadPreviousSession', function_name='A3A_fnc_loadPreviousSession'),
                        ASFunctionItem(file_name='fn_mineDialog.sqf', file_path='functions/Dialogs/fn_mineDialog.sqf', class_name='mineDialog', function_name='A3A_fnc_mineDialog'),
                        ASFunctionItem(file_name='fn_moveHQObject.sqf', file_path='functions/Dialogs/fn_moveHQObject.sqf', class_name='moveHQObject', function_name='A3A_fnc_moveHQObject'),
                        ASFunctionItem(file_name='fn_persistentSave.sqf', file_path='functions/Dialogs/fn_persistentSave.sqf', class_name='persistentSave', function_name='A3A_fnc_persistentSave'),
                        ASFunctionItem(file_name='fn_skiptime.sqf', file_path='functions/Dialogs/fn_skiptime.sqf', class_name='skiptime', function_name='A3A_fnc_skiptime'),
                        ASFunctionItem(file_name='fn_squadOptions.sqf', file_path='functions/Dialogs/fn_squadOptions.sqf', class_name='squadOptions', function_name='A3A_fnc_squadOptions'),
                        ASFunctionItem(file_name='fn_squadRecruit.sqf', file_path='functions/Dialogs/fn_squadRecruit.sqf', class_name='squadRecruit', function_name='A3A_fnc_squadRecruit'),
                        ASFunctionItem(file_name='fn_unit_recruit.sqf', file_path='functions/Dialogs/fn_unit_recruit.sqf', class_name='unit_recruit', function_name='A3A_fnc_unit_recruit')],
            'Garage': [ASFunctionItem(file_name='defineGarage.inc', file_path='functions/Garage/defineGarage.inc', class_name='defineGarage', function_name='A3A_fnc_defineGarage'),
                       ASFunctionItem(file_name='fn_addToPersonalGarage.sqf', file_path='functions/Garage/fn_addToPersonalGarage.sqf', class_name='addToPersonalGarage', function_name='A3A_fnc_addToPersonalGarage'),
                       ASFunctionItem(file_name='fn_addToPersonalGarageLocal.sqf', file_path='functions/Garage/fn_addToPersonalGarageLocal.sqf', class_name='addToPersonalGarageLocal', function_name='A3A_fnc_addToPersonalGarageLocal'),
                       ASFunctionItem(file_name='fn_attemptPlaceVehicle.sqf', file_path='functions/Garage/fn_attemptPlaceVehicle.sqf', class_name='attemptPlaceVehicle', function_name='A3A_fnc_attemptPlaceVehicle'),
                       ASFunctionItem(file_name='fn_displayVehiclePlacementMessage.sqf', file_path='functions/Garage/fn_displayVehiclePlacementMessage.sqf',
                                      class_name='displayVehiclePlacementMessage', function_name='A3A_fnc_displayVehiclePlacementMessage'),
                       ASFunctionItem(file_name='fn_garage.sqf', file_path='functions/Garage/fn_garage.sqf', class_name='garage', function_name='A3A_fnc_garage'),
                       ASFunctionItem(file_name='fn_garageVehicle.sqf', file_path='functions/Garage/fn_garageVehicle.sqf', class_name='garageVehicle', function_name='A3A_fnc_garageVehicle'),
                       ASFunctionItem(file_name='fn_getPersonalGarage.sqf', file_path='functions/Garage/fn_getPersonalGarage.sqf', class_name='getPersonalGarage', function_name='A3A_fnc_getPersonalGarage'),
                       ASFunctionItem(file_name='fn_getPersonalGarageLocal.sqf', file_path='functions/Garage/fn_getPersonalGarageLocal.sqf', class_name='getPersonalGarageLocal', function_name='A3A_fnc_getPersonalGarageLocal'),
                       ASFunctionItem(file_name='fn_handleVehPlacementCancelled.sqf', file_path='functions/Garage/fn_handleVehPlacementCancelled.sqf', class_name='handleVehPlacementCancelled', function_name='A3A_fnc_handleVehPlacementCancelled'),
                       ASFunctionItem(file_name='fn_placeEmptyVehicle.sqf', file_path='functions/Garage/fn_placeEmptyVehicle.sqf', class_name='placeEmptyVehicle', function_name='A3A_fnc_placeEmptyVehicle'),
                       ASFunctionItem(file_name='fn_setPersonalGarage.sqf', file_path='functions/Garage/fn_setPersonalGarage.sqf', class_name='setPersonalGarage', function_name='A3A_fnc_setPersonalGarage'),
                       ASFunctionItem(file_name='fn_setPersonalGarageLocal.sqf', file_path='functions/Garage/fn_setPersonalGarageLocal.sqf', class_name='setPersonalGarageLocal', function_name='A3A_fnc_setPersonalGarageLocal'),
                       ASFunctionItem(file_name='fn_vehPlacementBegin.sqf', file_path='functions/Garage/fn_vehPlacementBegin.sqf', class_name='vehPlacementBegin', function_name='A3A_fnc_vehPlacementBegin'),
                       ASFunctionItem(file_name='fn_vehPlacementCallbacks.sqf', file_path='functions/Garage/fn_vehPlacementCallbacks.sqf', class_name='vehPlacementCallbacks', function_name='A3A_fnc_vehPlacementCallbacks'),
                       ASFunctionItem(file_name='fn_vehPlacementCancel.sqf', file_path='functions/Garage/fn_vehPlacementCancel.sqf', class_name='vehPlacementCancel', function_name='A3A_fnc_vehPlacementCancel'),
                       ASFunctionItem(file_name='fn_vehPlacementChangeVehicle.sqf', file_path='functions/Garage/fn_vehPlacementChangeVehicle.sqf', class_name='vehPlacementChangeVehicle', function_name='A3A_fnc_vehPlacementChangeVehicle'),
                       ASFunctionItem(file_name='fn_vehPlacementCleanup.sqf', file_path='functions/Garage/fn_vehPlacementCleanup.sqf', class_name='vehPlacementCleanup', function_name='A3A_fnc_vehPlacementCleanup')],
            'Garrison': [ASFunctionItem(file_name='fn_addGarrison.sqf', file_path='functions/Garrison/fn_addGarrison.sqf', class_name='addGarrison', function_name='A3A_fnc_addGarrison'),
                         ASFunctionItem(file_name='fn_addRequested.sqf', file_path='functions/Garrison/fn_addRequested.sqf', class_name='addRequested', function_name='A3A_fnc_addRequested'),
                         ASFunctionItem(file_name='fn_checkGroupType.sqf', file_path='functions/Garrison/fn_checkGroupType.sqf', class_name='checkGroupType', function_name='A3A_fnc_checkGroupType'),
                         ASFunctionItem(file_name='fn_checkVehicleType.sqf', file_path='functions/Garrison/fn_checkVehicleType.sqf', class_name='checkVehicleType', function_name='A3A_fnc_checkVehicleType'),
                         ASFunctionItem(file_name='fn_countGarrison.sqf', file_path='functions/Garrison/fn_countGarrison.sqf', class_name='countGarrison', function_name='A3A_fnc_countGarrison'),
                         ASFunctionItem(file_name='fn_createGarrison.sqf', file_path='functions/Garrison/fn_createGarrison.sqf', class_name='createGarrison', function_name='A3A_fnc_createGarrison'),
                         ASFunctionItem(file_name='fn_createGarrisonLine.sqf', file_path='functions/Garrison/fn_createGarrisonLine.sqf', class_name='createGarrisonLine', function_name='A3A_fnc_createGarrisonLine'),
                         ASFunctionItem(file_name='fn_getGarrison.sqf', file_path='functions/Garrison/fn_getGarrison.sqf', class_name='getGarrison', function_name='A3A_fnc_getGarrison'),
                         ASFunctionItem(file_name='fn_getGarrisonRatio.sqf', file_path='functions/Garrison/fn_getGarrisonRatio.sqf', class_name='getGarrisonRatio', function_name='A3A_fnc_getGarrisonRatio'),
                         ASFunctionItem(file_name='fn_getGarrisonStatus.sqf', file_path='functions/Garrison/fn_getGarrisonStatus.sqf', class_name='getGarrisonStatus', function_name='A3A_fnc_getGarrisonStatus'),
                         ASFunctionItem(file_name='fn_getRequested.sqf', file_path='functions/Garrison/fn_getRequested.sqf', class_name='getRequested', function_name='A3A_fnc_getRequested'),
                         ASFunctionItem(file_name='fn_getVehicleCrew.sqf', file_path='functions/Garrison/fn_getVehicleCrew.sqf', class_name='getVehicleCrew', function_name='A3A_fnc_getVehicleCrew'),
                         ASFunctionItem(file_name='fn_initPreference.sqf', file_path='functions/Garrison/fn_initPreference.sqf', class_name='initPreference', function_name='A3A_fnc_initPreference'),
                         ASFunctionItem(file_name='fn_logArray.sqf', file_path='functions/Garrison/fn_logArray.sqf', class_name='logArray', function_name='A3A_fnc_logArray'),
                         ASFunctionItem(file_name='fn_replenishGarrison.sqf', file_path='functions/Garrison/fn_replenishGarrison.sqf', class_name='replenishGarrison', function_name='A3A_fnc_replenishGarrison'),
                         ASFunctionItem(file_name='fn_selectGroupType.sqf', file_path='functions/Garrison/fn_selectGroupType.sqf', class_name='selectGroupType', function_name='A3A_fnc_selectGroupType'),
                         ASFunctionItem(file_name='fn_selectReinfUnits.sqf', file_path='functions/Garrison/fn_selectReinfUnits.sqf', class_name='selectReinfUnits', function_name='A3A_fnc_selectReinfUnits'),
                         ASFunctionItem(file_name='fn_selectVehicleType.sqf', file_path='functions/Garrison/fn_selectVehicleType.sqf', class_name='selectVehicleType', function_name='A3A_fnc_selectVehicleType'),
                         ASFunctionItem(file_name='fn_shouldReinforce.sqf', file_path='functions/Garrison/fn_shouldReinforce.sqf', class_name='shouldReinforce', function_name='A3A_fnc_shouldReinforce'),
                         ASFunctionItem(file_name='fn_updateGarrison.sqf', file_path='functions/Garrison/fn_updateGarrison.sqf', class_name='updateGarrison', function_name='A3A_fnc_updateGarrison'),
                         ASFunctionItem(file_name='fn_updatePreference.sqf', file_path='functions/Garrison/fn_updatePreference.sqf', class_name='updatePreference', function_name='A3A_fnc_updatePreference'),
                         ASFunctionItem(file_name='fn_updateReinfState.sqf', file_path='functions/Garrison/fn_updateReinfState.sqf', class_name='updateReinfState', function_name='A3A_fnc_updateReinfState'),
                         ASFunctionItem(file_name='fn_updateVehicles.sqf', file_path='functions/Garrison/fn_updateVehicles.sqf', class_name='updateVehicles', function_name='A3A_fnc_updateVehicles'),
                         ASFunctionItem(file_name='notes', file_path='functions/Garrison/notes', class_name='notes', function_name='A3A_fnc_notes'),
                         ASFunctionItem(file_name='testScripts', file_path='functions/Garrison/testScripts', class_name='testScripts', function_name='A3A_fnc_testScripts')],
            'Intel': [ASFunctionItem(file_name='fn_getVehicleIntel.sqf', file_path='functions/Intel/fn_getVehicleIntel.sqf', class_name='getVehicleIntel', function_name='A3A_fnc_getVehicleIntel'),
                      ASFunctionItem(file_name='fn_placeIntel.sqf', file_path='functions/Intel/fn_placeIntel.sqf', class_name='placeIntel', function_name='A3A_fnc_placeIntel'),
                      ASFunctionItem(file_name='fn_searchIntelOnDocument.sqf', file_path='functions/Intel/fn_searchIntelOnDocument.sqf', class_name='searchIntelOnDocument', function_name='A3A_fnc_searchIntelOnDocument'),
                      ASFunctionItem(file_name='fn_searchIntelOnLaptop.sqf', file_path='functions/Intel/fn_searchIntelOnLaptop.sqf', class_name='searchIntelOnLaptop', function_name='A3A_fnc_searchIntelOnLaptop'),
                      ASFunctionItem(file_name='fn_searchIntelOnLeader.sqf', file_path='functions/Intel/fn_searchIntelOnLeader.sqf', class_name='searchIntelOnLeader', function_name='A3A_fnc_searchIntelOnLeader'),
                      ASFunctionItem(file_name='fn_selectIntel.sqf', file_path='functions/Intel/fn_selectIntel.sqf', class_name='selectIntel', function_name='A3A_fnc_selectIntel'),
                      ASFunctionItem(file_name='fn_showIntel.sqf', file_path='functions/Intel/fn_showIntel.sqf', class_name='showIntel', function_name='A3A_fnc_showIntel'),
                      ASFunctionItem(file_name='helpScripts', file_path='functions/Intel/helpScripts', class_name='helpScripts', function_name='A3A_fnc_helpScripts')],
            'LTC': [ASFunctionItem(file_name='fn_canLoot.sqf', file_path='functions/LTC/fn_canLoot.sqf', class_name='canLoot', function_name='A3A_fnc_canLoot'),
                    ASFunctionItem(file_name='fn_canTransfer.sqf', file_path='functions/LTC/fn_canTransfer.sqf', class_name='canTransfer', function_name='A3A_fnc_canTransfer'),
                    ASFunctionItem(file_name='fn_carryCrate.sqf', file_path='functions/LTC/fn_carryCrate.sqf', class_name='carryCrate', function_name='A3A_fnc_carryCrate'),
                    ASFunctionItem(file_name='fn_initLootToCrate.sqf', file_path='functions/LTC/fn_initLootToCrate.sqf', class_name='initLootToCrate', function_name='A3A_fnc_initLootToCrate'),
                    ASFunctionItem(file_name='fn_lootFromContainer.sqf', file_path='functions/LTC/fn_lootFromContainer.sqf', class_name='lootFromContainer', function_name='A3A_fnc_lootFromContainer'),
                    ASFunctionItem(file_name='fn_lootToCrate.sqf', file_path='functions/LTC/fn_lootToCrate.sqf', class_name='lootToCrate', function_name='A3A_fnc_lootToCrate'),
                    ASFunctionItem(file_name='fn_spawnCrate.sqf', file_path='functions/LTC/fn_spawnCrate.sqf', class_name='spawnCrate', function_name='A3A_fnc_spawnCrate')],
            'Missions': [ASFunctionItem(file_name='fn_AS_Official.sqf', file_path='functions/Missions/fn_AS_Official.sqf', class_name='AS_Official', function_name='A3A_fnc_AS_Official'),
                         ASFunctionItem(file_name='fn_AS_specOP.sqf', file_path='functions/Missions/fn_AS_specOP.sqf', class_name='AS_specOP', function_name='A3A_fnc_AS_specOP'),
                         ASFunctionItem(file_name='fn_AS_Traitor.sqf', file_path='functions/Missions/fn_AS_Traitor.sqf', class_name='AS_Traitor', function_name='A3A_fnc_AS_Traitor'),
                         ASFunctionItem(file_name='fn_attackHQ.sqf', file_path='functions/Missions/fn_attackHQ.sqf', class_name='attackHQ', function_name='A3A_fnc_attackHQ'),
                         ASFunctionItem(file_name='fn_convoy.sqf', file_path='functions/Missions/fn_convoy.sqf', class_name='convoy', function_name='A3A_fnc_convoy'),
                         ASFunctionItem(file_name='fn_CON_Outpost.sqf', file_path='functions/Missions/fn_CON_Outpost.sqf', class_name='CON_Outpost', function_name='A3A_fnc_CON_Outpost'),
                         ASFunctionItem(file_name='fn_deleteTask.sqf', file_path='functions/Missions/fn_deleteTask.sqf', class_name='deleteTask', function_name='A3A_fnc_deleteTask'),
                         ASFunctionItem(file_name='fn_DES_Antenna.sqf', file_path='functions/Missions/fn_DES_Antenna.sqf', class_name='DES_Antenna', function_name='A3A_fnc_DES_Antenna'),
                         ASFunctionItem(file_name='fn_DES_Heli.sqf', file_path='functions/Missions/fn_DES_Heli.sqf', class_name='DES_Heli', function_name='A3A_fnc_DES_Heli'),
                         ASFunctionItem(file_name='fn_DES_Vehicle.sqf', file_path='functions/Missions/fn_DES_Vehicle.sqf', class_name='DES_Vehicle', function_name='A3A_fnc_DES_Vehicle'),
                         ASFunctionItem(file_name='fn_LOG_Ammo.sqf', file_path='functions/Missions/fn_LOG_Ammo.sqf', class_name='LOG_Ammo', function_name='A3A_fnc_LOG_Ammo'),
                         ASFunctionItem(file_name='fn_LOG_Bank.sqf', file_path='functions/Missions/fn_LOG_Bank.sqf', class_name='LOG_Bank', function_name='A3A_fnc_LOG_Bank'),
                         ASFunctionItem(file_name='fn_LOG_Salvage.sqf', file_path='functions/Missions/fn_LOG_Salvage.sqf', class_name='LOG_Salvage', function_name='A3A_fnc_LOG_Salvage'),
                         ASFunctionItem(file_name='fn_LOG_Supplies.sqf', file_path='functions/Missions/fn_LOG_Supplies.sqf', class_name='LOG_Supplies', function_name='A3A_fnc_LOG_Supplies'),
                         ASFunctionItem(file_name='fn_missionRequest.sqf', file_path='functions/Missions/fn_missionRequest.sqf', class_name='missionRequest', function_name='A3A_fnc_missionRequest'),
                         ASFunctionItem(file_name='fn_REP_Antenna.sqf', file_path='functions/Missions/fn_REP_Antenna.sqf', class_name='REP_Antenna', function_name='A3A_fnc_REP_Antenna'),
                         ASFunctionItem(file_name='fn_RES_Prisoners.sqf', file_path='functions/Missions/fn_RES_Prisoners.sqf', class_name='RES_Prisoners', function_name='A3A_fnc_RES_Prisoners'),
                         ASFunctionItem(file_name='fn_RES_Refugees.sqf', file_path='functions/Missions/fn_RES_Refugees.sqf', class_name='RES_Refugees', function_name='A3A_fnc_RES_Refugees'),
                         ASFunctionItem(file_name='fn_taskUpdate.sqf', file_path='functions/Missions/fn_taskUpdate.sqf', class_name='taskUpdate', function_name='A3A_fnc_taskUpdate'),
                         ASFunctionItem(file_name='fn_underAttack.sqf', file_path='functions/Missions/fn_underAttack.sqf', class_name='underAttack', function_name='A3A_fnc_underAttack')],
            'ModsAndDLC': [ASFunctionItem(file_name='fn_getModOfConfigClass.sqf', file_path='functions/ModsAndDLC/fn_getModOfConfigClass.sqf', class_name='getModOfConfigClass', function_name='A3A_fnc_getModOfConfigClass'),
                           ASFunctionItem(file_name='fn_initDisabledMods.sqf', file_path='functions/ModsAndDLC/fn_initDisabledMods.sqf', class_name='initDisabledMods', function_name='A3A_fnc_initDisabledMods'),
                           ASFunctionItem(file_name='fn_isModNameVanilla.sqf', file_path='functions/ModsAndDLC/fn_isModNameVanilla.sqf', class_name='isModNameVanilla', function_name='A3A_fnc_isModNameVanilla')],
            'OrgPlayers': [ASFunctionItem(file_name='fn_assignBossIfNone.sqf', file_path='functions/OrgPlayers/fn_assignBossIfNone.sqf', class_name='assignBossIfNone', function_name='A3A_fnc_assignBossIfNone'),
                           ASFunctionItem(file_name='fn_donateMoney.sqf', file_path='functions/OrgPlayers/fn_donateMoney.sqf', class_name='donateMoney', function_name='A3A_fnc_donateMoney'),
                           ASFunctionItem(file_name='fn_isMember.sqf', file_path='functions/OrgPlayers/fn_isMember.sqf', class_name='isMember', function_name='A3A_fnc_isMember'),
                           ASFunctionItem(file_name='fn_makePlayerBossIfEligible.sqf', file_path='functions/OrgPlayers/fn_makePlayerBossIfEligible.sqf', class_name='makePlayerBossIfEligible', function_name='A3A_fnc_makePlayerBossIfEligible'),
                           ASFunctionItem(file_name='fn_memberAdd.sqf', file_path='functions/OrgPlayers/fn_memberAdd.sqf', class_name='memberAdd', function_name='A3A_fnc_memberAdd'),
                           ASFunctionItem(file_name='fn_membersList.sqf', file_path='functions/OrgPlayers/fn_membersList.sqf', class_name='membersList', function_name='A3A_fnc_membersList'),
                           ASFunctionItem(file_name='fn_playerScoreAdd.sqf', file_path='functions/OrgPlayers/fn_playerScoreAdd.sqf', class_name='playerScoreAdd', function_name='A3A_fnc_playerScoreAdd'),
                           ASFunctionItem(file_name='fn_promotePlayer.sqf', file_path='functions/OrgPlayers/fn_promotePlayer.sqf', class_name='promotePlayer', function_name='A3A_fnc_promotePlayer'),
                           ASFunctionItem(file_name='fn_ranksMP.sqf', file_path='functions/OrgPlayers/fn_ranksMP.sqf', class_name='ranksMP', function_name='A3A_fnc_ranksMP'),
                           ASFunctionItem(file_name='fn_resourcesPlayer.sqf', file_path='functions/OrgPlayers/fn_resourcesPlayer.sqf', class_name='resourcesPlayer', function_name='A3A_fnc_resourcesPlayer'),
                           ASFunctionItem(file_name='fn_theBossSteal.sqf', file_path='functions/OrgPlayers/fn_theBossSteal.sqf', class_name='theBossSteal', function_name='A3A_fnc_theBossSteal'),
                           ASFunctionItem(file_name='fn_theBossToggleEligibility.sqf', file_path='functions/OrgPlayers/fn_theBossToggleEligibility.sqf', class_name='theBossToggleEligibility', function_name='A3A_fnc_theBossToggleEligibility'),
                           ASFunctionItem(file_name='fn_theBossTransfer.sqf', file_path='functions/OrgPlayers/fn_theBossTransfer.sqf', class_name='theBossTransfer', function_name='A3A_fnc_theBossTransfer'),
                           ASFunctionItem(file_name='fn_tierCheck.sqf', file_path='functions/OrgPlayers/fn_tierCheck.sqf', class_name='tierCheck', function_name='A3A_fnc_tierCheck')],
            'Pathfinding': [ASFunctionItem(file_name='fn_calculateH.sqf', file_path='functions/Pathfinding/fn_calculateH.sqf', class_name='calculateH', function_name='A3A_fnc_calculateH'),
                            ASFunctionItem(file_name='fn_findNearestNavPoint.sqf', file_path='functions/Pathfinding/fn_findNearestNavPoint.sqf', class_name='findNearestNavPoint', function_name='A3A_fnc_findNearestNavPoint'),
                            ASFunctionItem(file_name='fn_findPath.sqf', file_path='functions/Pathfinding/fn_findPath.sqf', class_name='findPath', function_name='A3A_fnc_findPath'),
                            ASFunctionItem(file_name='fn_getClosestMainMarker.sqf', file_path='functions/Pathfinding/fn_getClosestMainMarker.sqf', class_name='getClosestMainMarker', function_name='A3A_fnc_getClosestMainMarker'),
                            ASFunctionItem(file_name='fn_getMainMarkers.sqf', file_path='functions/Pathfinding/fn_getMainMarkers.sqf', class_name='getMainMarkers', function_name='A3A_fnc_getMainMarkers'),
                            ASFunctionItem(file_name='fn_getNavConnections.sqf', file_path='functions/Pathfinding/fn_getNavConnections.sqf', class_name='getNavConnections', function_name='A3A_fnc_getNavConnections'),
                            ASFunctionItem(file_name='fn_getNavPos.sqf', file_path='functions/Pathfinding/fn_getNavPos.sqf', class_name='getNavPos', function_name='A3A_fnc_getNavPos'),
                            ASFunctionItem(file_name='fn_loadNavGrid.sqf', file_path='functions/Pathfinding/fn_loadNavGrid.sqf', class_name='loadNavGrid', function_name='A3A_fnc_loadNavGrid'),
                            ASFunctionItem(file_name='fn_setNavOnMarker.sqf', file_path='functions/Pathfinding/fn_setNavOnMarker.sqf', class_name='setNavOnMarker', function_name='A3A_fnc_setNavOnMarker')],
            'Punishment': [ASFunctionItem(file_name='fn_outOfBounds.sqf', file_path='functions/Punishment/fn_outOfBounds.sqf', class_name='outOfBounds', function_name='A3A_fnc_outOfBounds'),
                           ASFunctionItem(file_name='fn_punishment.sqf', file_path='functions/Punishment/fn_punishment.sqf', class_name='punishment', function_name='A3A_fnc_punishment'),
                           ASFunctionItem(file_name='fn_punishment_addActionForgive.sqf', file_path='functions/Punishment/fn_punishment_addActionForgive.sqf',
                                          class_name='punishment_addActionForgive', function_name='A3A_fnc_punishment_addActionForgive'),
                           ASFunctionItem(file_name='fn_punishment_checkStatus.sqf', file_path='functions/Punishment/fn_punishment_checkStatus.sqf', class_name='punishment_checkStatus', function_name='A3A_fnc_punishment_checkStatus'),
                           ASFunctionItem(file_name='fn_punishment_dataGet.sqf', file_path='functions/Punishment/fn_punishment_dataGet.sqf', class_name='punishment_dataGet', function_name='A3A_fnc_punishment_dataGet'),
                           ASFunctionItem(file_name='fn_punishment_dataNamespace.sqf', file_path='functions/Punishment/fn_punishment_dataNamespace.sqf', class_name='punishment_dataNamespace', function_name='A3A_fnc_punishment_dataNamespace'),
                           ASFunctionItem(file_name='fn_punishment_dataRem.sqf', file_path='functions/Punishment/fn_punishment_dataRem.sqf', class_name='punishment_dataRem', function_name='A3A_fnc_punishment_dataRem'),
                           ASFunctionItem(file_name='fn_punishment_dataSet.sqf', file_path='functions/Punishment/fn_punishment_dataSet.sqf', class_name='punishment_dataSet', function_name='A3A_fnc_punishment_dataSet'),
                           ASFunctionItem(file_name='fn_punishment_FF.sqf', file_path='functions/Punishment/fn_punishment_FF.sqf', class_name='punishment_FF', function_name='A3A_fnc_punishment_FF'),
                           ASFunctionItem(file_name='fn_punishment_FF_AddEH.sqf', file_path='functions/Punishment/fn_punishment_FF_AddEH.sqf', class_name='punishment_FF_AddEH', function_name='A3A_fnc_punishment_FF_AddEH'),
                           ASFunctionItem(file_name='fn_punishment_FF_checkNearHQ.sqf', file_path='functions/Punishment/fn_punishment_FF_checkNearHQ.sqf', class_name='punishment_FF_checkNearHQ', function_name='A3A_fnc_punishment_FF_checkNearHQ'),
                           ASFunctionItem(file_name='fn_punishment_notifyAdmin.sqf', file_path='functions/Punishment/fn_punishment_notifyAdmin.sqf', class_name='punishment_notifyAdmin', function_name='A3A_fnc_punishment_notifyAdmin'),
                           ASFunctionItem(file_name='fn_punishment_notPlayer.sqf', file_path='functions/Punishment/fn_punishment_notPlayer.sqf', class_name='punishment_notPlayer', function_name='A3A_fnc_punishment_notPlayer'),
                           ASFunctionItem(file_name='fn_punishment_oceanGulag.sqf', file_path='functions/Punishment/fn_punishment_oceanGulag.sqf', class_name='punishment_oceanGulag', function_name='A3A_fnc_punishment_oceanGulag'),
                           ASFunctionItem(file_name='fn_punishment_release.sqf', file_path='functions/Punishment/fn_punishment_release.sqf', class_name='punishment_release', function_name='A3A_fnc_punishment_release'),
                           ASFunctionItem(file_name='fn_punishment_removeActionForgive.sqf', file_path='functions/Punishment/fn_punishment_removeActionForgive.sqf',
                                          class_name='punishment_removeActionForgive', function_name='A3A_fnc_punishment_removeActionForgive'),
                           ASFunctionItem(file_name='fn_punishment_sentence_client.sqf', file_path='functions/Punishment/fn_punishment_sentence_client.sqf', class_name='punishment_sentence_client', function_name='A3A_fnc_punishment_sentence_client'),
                           ASFunctionItem(file_name='fn_punishment_sentence_server.sqf', file_path='functions/Punishment/fn_punishment_sentence_server.sqf', class_name='punishment_sentence_server', function_name='A3A_fnc_punishment_sentence_server')],
            'REINF': [ASFunctionItem(file_name='fn_addBombRun.sqf', file_path='functions/REINF/fn_addBombRun.sqf', class_name='addBombRun', function_name='A3A_fnc_addBombRun'),
                      ASFunctionItem(file_name='fn_addFIAsquadHC.sqf', file_path='functions/REINF/fn_addFIAsquadHC.sqf', class_name='addFIAsquadHC', function_name='A3A_fnc_addFIAsquadHC'),
                      ASFunctionItem(file_name='fn_addFIAveh.sqf', file_path='functions/REINF/fn_addFIAveh.sqf', class_name='addFIAveh', function_name='A3A_fnc_addFIAveh'),
                      ASFunctionItem(file_name='fn_addSquadVeh.sqf', file_path='functions/REINF/fn_addSquadVeh.sqf', class_name='addSquadVeh', function_name='A3A_fnc_addSquadVeh'),
                      ASFunctionItem(file_name='fn_autoGarrison.sqf', file_path='functions/REINF/fn_autoGarrison.sqf', class_name='autoGarrison', function_name='A3A_fnc_autoGarrison'),
                      ASFunctionItem(file_name='fn_build.sqf', file_path='functions/REINF/fn_build.sqf', class_name='build', function_name='A3A_fnc_build'),
                      ASFunctionItem(file_name='fn_buildCreateVehicleCallback.sqf', file_path='functions/REINF/fn_buildCreateVehicleCallback.sqf', class_name='buildCreateVehicleCallback', function_name='A3A_fnc_buildCreateVehicleCallback'),
                      ASFunctionItem(file_name='fn_buildMinefield.sqf', file_path='functions/REINF/fn_buildMinefield.sqf', class_name='buildMinefield', function_name='A3A_fnc_buildMinefield'),
                      ASFunctionItem(file_name='fn_enemyNearCheck.sqf', file_path='functions/REINF/fn_enemyNearCheck.sqf', class_name='enemyNearCheck', function_name='A3A_fnc_enemyNearCheck'),
                      ASFunctionItem(file_name='fn_equipRebel.sqf', file_path='functions/REINF/fn_equipRebel.sqf', class_name='equipRebel', function_name='A3A_fnc_equipRebel'),
                      ASFunctionItem(file_name='fn_FIAinit.sqf', file_path='functions/REINF/fn_FIAinit.sqf', class_name='FIAinit', function_name='A3A_fnc_FIAinit'),
                      ASFunctionItem(file_name='fn_FIAskillAdd.sqf', file_path='functions/REINF/fn_FIAskillAdd.sqf', class_name='FIAskillAdd', function_name='A3A_fnc_FIAskillAdd'),
                      ASFunctionItem(file_name='fn_garrisonAdd.sqf', file_path='functions/REINF/fn_garrisonAdd.sqf', class_name='garrisonAdd', function_name='A3A_fnc_garrisonAdd'),
                      ASFunctionItem(file_name='fn_garrisonDialog.sqf', file_path='functions/REINF/fn_garrisonDialog.sqf', class_name='garrisonDialog', function_name='A3A_fnc_garrisonDialog'),
                      ASFunctionItem(file_name='fn_NATObomb.sqf', file_path='functions/REINF/fn_NATObomb.sqf', class_name='NATObomb', function_name='A3A_fnc_NATObomb'),
                      ASFunctionItem(file_name='fn_NATOQuadbike.sqf', file_path='functions/REINF/fn_NATOQuadbike.sqf', class_name='NATOQuadbike', function_name='A3A_fnc_NATOQuadbike'),
                      ASFunctionItem(file_name='fn_postmortem.sqf', file_path='functions/REINF/fn_postmortem.sqf', class_name='postmortem', function_name='A3A_fnc_postmortem'),
                      ASFunctionItem(file_name='fn_reDress.sqf', file_path='functions/REINF/fn_reDress.sqf', class_name='reDress', function_name='A3A_fnc_reDress'),
                      ASFunctionItem(file_name='fn_reinfPlayer.sqf', file_path='functions/REINF/fn_reinfPlayer.sqf', class_name='reinfPlayer', function_name='A3A_fnc_reinfPlayer'),
                      ASFunctionItem(file_name='fn_stealStatic.sqf', file_path='functions/REINF/fn_stealStatic.sqf', class_name='stealStatic', function_name='A3A_fnc_stealStatic'),
                      ASFunctionItem(file_name='fn_vehiclePrice.sqf', file_path='functions/REINF/fn_vehiclePrice.sqf', class_name='vehiclePrice', function_name='A3A_fnc_vehiclePrice'),
                      ASFunctionItem(file_name='fn_vehStats.sqf', file_path='functions/REINF/fn_vehStats.sqf', class_name='vehStats', function_name='A3A_fnc_vehStats')],
            'Reinforcements': [ASFunctionItem(file_name='fn_landHelicopter.sqf', file_path='functions/Reinforcements/fn_landHelicopter.sqf', class_name='landHelicopter', function_name='A3A_fnc_landHelicopter')],
            'Revive': [ASFunctionItem(file_name='fn_actionRevive.sqf', file_path='functions/Revive/fn_actionRevive.sqf', class_name='actionRevive', function_name='A3A_fnc_actionRevive'),
                       ASFunctionItem(file_name='fn_carry.sqf', file_path='functions/Revive/fn_carry.sqf', class_name='carry', function_name='A3A_fnc_carry'),
                       ASFunctionItem(file_name='fn_fatalWound.sqf', file_path='functions/Revive/fn_fatalWound.sqf', class_name='fatalWound', function_name='A3A_fnc_fatalWound'),
                       ASFunctionItem(file_name='fn_handleDamage.sqf', file_path='functions/Revive/fn_handleDamage.sqf', class_name='handleDamage', function_name='A3A_fnc_handleDamage'),
                       ASFunctionItem(file_name='fn_handleDamageAAF.sqf', file_path='functions/Revive/fn_handleDamageAAF.sqf', class_name='handleDamageAAF', function_name='A3A_fnc_handleDamageAAF'),
                       ASFunctionItem(file_name='fn_initRevive.sqf', file_path='functions/Revive/fn_initRevive.sqf', class_name='initRevive', function_name='A3A_fnc_initRevive'),
                       ASFunctionItem(file_name='fn_isMedic.sqf', file_path='functions/Revive/fn_isMedic.sqf', class_name='isMedic', function_name='A3A_fnc_isMedic'),
                       ASFunctionItem(file_name='fn_respawn.sqf', file_path='functions/Revive/fn_respawn.sqf', class_name='respawn', function_name='A3A_fnc_respawn'),
                       ASFunctionItem(file_name='fn_unconscious.sqf', file_path='functions/Revive/fn_unconscious.sqf', class_name='unconscious', function_name='A3A_fnc_unconscious'),
                       ASFunctionItem(file_name='fn_unconsciousAAF.sqf', file_path='functions/Revive/fn_unconsciousAAF.sqf', class_name='unconsciousAAF', function_name='A3A_fnc_unconsciousAAF')],
            'Runways': [ASFunctionItem(file_name='fn_getRunwayTakeoffForAirportMarker.sqf', file_path='functions/Runways/fn_getRunwayTakeoffForAirportMarker.sqf', class_name='getRunwayTakeoffForAirportMarker', function_name='A3A_fnc_getRunwayTakeoffForAirportMarker'),
                        ASFunctionItem(file_name='fn_runwayInfo.sqf', file_path='functions/Runways/fn_runwayInfo.sqf', class_name='runwayInfo', function_name='A3A_fnc_runwayInfo')],
            'SalvageRope': [ASFunctionItem(file_name='fn_salvageRope.sqf', file_path='functions/SalvageRope/fn_salvageRope.sqf', class_name='salvageRope', function_name='A3A_fnc_salvageRope')],
            'Save': [ASFunctionItem(file_name='fn_deleteSave.sqf', file_path='functions/Save/fn_deleteSave.sqf', class_name='deleteSave', function_name='A3A_fnc_deleteSave'),
                     ASFunctionItem(file_name='fn_getStatVariable.sqf', file_path='functions/Save/fn_getStatVariable.sqf', class_name='getStatVariable', function_name='A3A_fnc_getStatVariable'),
                     ASFunctionItem(file_name='fn_loadPlayer.sqf', file_path='functions/Save/fn_loadPlayer.sqf', class_name='loadPlayer', function_name='A3A_fnc_loadPlayer'),
                     ASFunctionItem(file_name='fn_loadServer.sqf', file_path='functions/Save/fn_loadServer.sqf', class_name='loadServer', function_name='A3A_fnc_loadServer'),
                     ASFunctionItem(file_name='fn_loadStat.sqf', file_path='functions/Save/fn_loadStat.sqf', class_name='loadStat', function_name='A3A_fnc_loadStat'),
                     ASFunctionItem(file_name='fn_playerHasSave.sqf', file_path='functions/Save/fn_playerHasSave.sqf', class_name='playerHasSave', function_name='A3A_fnc_playerHasSave'),
                     ASFunctionItem(file_name='fn_resetPlayer.sqf', file_path='functions/Save/fn_resetPlayer.sqf', class_name='resetPlayer', function_name='A3A_fnc_resetPlayer'),
                     ASFunctionItem(file_name='fn_retrievePlayerStat.sqf', file_path='functions/Save/fn_retrievePlayerStat.sqf', class_name='retrievePlayerStat', function_name='A3A_fnc_retrievePlayerStat'),
                     ASFunctionItem(file_name='fn_returnSavedStat.sqf', file_path='functions/Save/fn_returnSavedStat.sqf', class_name='returnSavedStat', function_name='A3A_fnc_returnSavedStat'),
                     ASFunctionItem(file_name='fn_saveLoop.sqf', file_path='functions/Save/fn_saveLoop.sqf', class_name='saveLoop', function_name='A3A_fnc_saveLoop'),
                     ASFunctionItem(file_name='fn_savePlayer.sqf', file_path='functions/Save/fn_savePlayer.sqf', class_name='savePlayer', function_name='A3A_fnc_savePlayer'),
                     ASFunctionItem(file_name='fn_savePlayerStat.sqf', file_path='functions/Save/fn_savePlayerStat.sqf', class_name='savePlayerStat', function_name='A3A_fnc_savePlayerStat'),
                     ASFunctionItem(file_name='fn_setStatVariable.sqf', file_path='functions/Save/fn_setStatVariable.sqf', class_name='setStatVariable', function_name='A3A_fnc_setStatVariable'),
                     ASFunctionItem(file_name='fn_varNameToSaveName.sqf', file_path='functions/Save/fn_varNameToSaveName.sqf', class_name='varNameToSaveName', function_name='A3A_fnc_varNameToSaveName')],
            'Templates': [ASFunctionItem(file_name='fn_aceModCompat.sqf', file_path='functions/Templates/fn_aceModCompat.sqf', class_name='aceModCompat', function_name='A3A_fnc_aceModCompat'),
                          ASFunctionItem(file_name='fn_getLoadout.sqf', file_path='functions/Templates/fn_getLoadout.sqf', class_name='getLoadout', function_name='A3A_fnc_getLoadout'),
                          ASFunctionItem(file_name='fn_ifaModCompat.sqf', file_path='functions/Templates/fn_ifaModCompat.sqf', class_name='ifaModCompat', function_name='A3A_fnc_ifaModCompat'),
                          ASFunctionItem(file_name='fn_rhsModCompat.sqf', file_path='functions/Templates/fn_rhsModCompat.sqf', class_name='rhsModCompat', function_name='A3A_fnc_rhsModCompat')],
            'UI': [ASFunctionItem(file_name='fn_customHint.sqf', file_path='functions/UI/fn_customHint.sqf', class_name='customHint', function_name='A3A_fnc_customHint'),
                   ASFunctionItem(file_name='fn_customHintDismiss.sqf', file_path='functions/UI/fn_customHintDismiss.sqf', class_name='customHintDismiss', function_name='A3A_fnc_customHintDismiss'),
                   ASFunctionItem(file_name='fn_customHintInit.sqf', file_path='functions/UI/fn_customHintInit.sqf', class_name='customHintInit', function_name='A3A_fnc_customHintInit'),
                   ASFunctionItem(file_name='fn_customHintRender.sqf', file_path='functions/UI/fn_customHintRender.sqf', class_name='customHintRender', function_name='A3A_fnc_customHintRender'),
                   ASFunctionItem(file_name='fn_shader_ratioToHex.sqf', file_path='functions/UI/fn_shader_ratioToHex.sqf', class_name='shader_ratioToHex', function_name='A3A_fnc_shader_ratioToHex'),
                   ASFunctionItem(file_name='images', file_path='functions/UI/images', class_name='images', function_name='A3A_fnc_images')],
            'Undercover': [ASFunctionItem(file_name='fn_goUndercover.sqf', file_path='functions/Undercover/fn_goUndercover.sqf', class_name='goUndercover', function_name='A3A_fnc_goUndercover'),
                           ASFunctionItem(file_name='fn_initUndercover.sqf', file_path='functions/Undercover/fn_initUndercover.sqf', class_name='initUndercover', function_name='A3A_fnc_initUndercover')],
            'Utility': [ASFunctionItem(file_name='fn_basicBackpack.sqf', file_path='functions/Utility/fn_basicBackpack.sqf', class_name='basicBackpack', function_name='A3A_fnc_basicBackpack'),
                        ASFunctionItem(file_name='fn_createDataObject.sqf', file_path='functions/Utility/fn_createDataObject.sqf', class_name='createDataObject', function_name='A3A_fnc_createDataObject'),
                        ASFunctionItem(file_name='fn_createNamespace.sqf', file_path='functions/Utility/fn_createNamespace.sqf', class_name='createNamespace', function_name='A3A_fnc_createNamespace'),
                        ASFunctionItem(file_name='fn_dateToTimeString.sqf', file_path='functions/Utility/fn_dateToTimeString.sqf', class_name='dateToTimeString', function_name='A3A_fnc_dateToTimeString'),
                        ASFunctionItem(file_name='fn_generateRoadsDB.sqf', file_path='functions/Utility/fn_generateRoadsDB.sqf', class_name='generateRoadsDB', function_name='A3A_fnc_generateRoadsDB'),
                        ASFunctionItem(file_name='fn_getRoadDirection.sqf', file_path='functions/Utility/fn_getRoadDirection.sqf', class_name='getRoadDirection', function_name='A3A_fnc_getRoadDirection'),
                        ASFunctionItem(file_name='fn_log.sqf', file_path='functions/Utility/fn_log.sqf', class_name='log', function_name='A3A_fnc_log'),
                        ASFunctionItem(file_name='fn_vehicleWillCollideAtPosition.sqf', file_path='functions/Utility/fn_vehicleWillCollideAtPosition.sqf', class_name='vehicleWillCollideAtPosition', function_name='A3A_fnc_vehicleWillCollideAtPosition')],
            'init': [ASFunctionItem(file_name='fn_cityinfo.sqf', file_path='functions/init/fn_cityinfo.sqf', class_name='cityinfo', function_name='A3A_fnc_cityinfo'),
                     ASFunctionItem(file_name='fn_credits.sqf', file_path='functions/init/fn_credits.sqf', class_name='credits', function_name='A3A_fnc_credits'),
                     ASFunctionItem(file_name='fn_initACEUnconsciousHandler.sqf', file_path='functions/init/fn_initACEUnconsciousHandler.sqf', class_name='initACEUnconsciousHandler', function_name='A3A_fnc_initACEUnconsciousHandler'),
                     ASFunctionItem(file_name='fn_initClient.sqf', file_path='functions/init/fn_initClient.sqf', class_name='initClient', function_name='A3A_fnc_initClient'),
                     ASFunctionItem(file_name='fn_initFuncs.sqf', file_path='functions/init/fn_initFuncs.sqf', class_name='initFuncs', function_name='A3A_fnc_initFuncs'),
                     ASFunctionItem(file_name='fn_initGarrisons.sqf', file_path='functions/init/fn_initGarrisons.sqf', class_name='initGarrisons', function_name='A3A_fnc_initGarrisons'),
                     ASFunctionItem(file_name='fn_initGetMissionPath.sqf', file_path='functions/init/fn_initGetMissionPath.sqf', class_name='initGetMissionPath', function_name='A3A_fnc_initGetMissionPath'),
                     ASFunctionItem(file_name='fn_initServer.sqf', file_path='functions/init/fn_initServer.sqf', class_name='initServer', function_name='A3A_fnc_initServer'),
                     ASFunctionItem(file_name='fn_initSnowFall.sqf', file_path='functions/init/fn_initSnowFall.sqf', class_name='initSnowFall', function_name='A3A_fnc_initSnowFall'),
                     ASFunctionItem(file_name='fn_initSpawnPlaces.sqf', file_path='functions/init/fn_initSpawnPlaces.sqf', class_name='initSpawnPlaces', function_name='A3A_fnc_initSpawnPlaces'),
                     ASFunctionItem(file_name='fn_initVar.sqf', file_path='functions/init/fn_initVar.sqf', class_name='initVar', function_name='A3A_fnc_initVar'),
                     ASFunctionItem(file_name='fn_initVarClient.sqf', file_path='functions/init/fn_initVarClient.sqf', class_name='initVarClient', function_name='A3A_fnc_initVarClient'),
                     ASFunctionItem(file_name='fn_initVarCommon.sqf', file_path='functions/init/fn_initVarCommon.sqf', class_name='initVarCommon', function_name='A3A_fnc_initVarCommon'),
                     ASFunctionItem(file_name='fn_initVarServer.sqf', file_path='functions/init/fn_initVarServer.sqf', class_name='initVarServer', function_name='A3A_fnc_initVarServer'),
                     ASFunctionItem(file_name='fn_initZones.sqf', file_path='functions/init/fn_initZones.sqf', class_name='initZones', function_name='A3A_fnc_initZones'),
                     ASFunctionItem(file_name='fn_modBlacklist.sqf', file_path='functions/init/fn_modBlacklist.sqf', class_name='modBlacklist', function_name='A3A_fnc_modBlacklist'),
                     ASFunctionItem(file_name='fn_playerMarkers.sqf', file_path='functions/init/fn_playerMarkers.sqf', class_name='playerMarkers', function_name='A3A_fnc_playerMarkers'),
                     ASFunctionItem(file_name='fn_prepareMarkerArrays.sqf', file_path='functions/init/fn_prepareMarkerArrays.sqf', class_name='prepareMarkerArrays', function_name='A3A_fnc_prepareMarkerArrays'),
                     ASFunctionItem(file_name='fn_reinitY.sqf', file_path='functions/init/fn_reinitY.sqf', class_name='reinitY', function_name='A3A_fnc_reinitY'),
                     ASFunctionItem(file_name='fn_resourcecheck.sqf', file_path='functions/init/fn_resourcecheck.sqf', class_name='resourcecheck', function_name='A3A_fnc_resourcecheck'),
                     ASFunctionItem(file_name='fn_tags.sqf', file_path='functions/init/fn_tags.sqf', class_name='tags', function_name='A3A_fnc_tags')],
            'pvp': [ASFunctionItem(file_name='fn_playerHasBeenPvPCheck.sqf', file_path='functions/pvp/fn_playerHasBeenPvPCheck.sqf', class_name='playerHasBeenPvPCheck', function_name='A3A_fnc_playerHasBeenPvPCheck'),
                    ASFunctionItem(file_name='fn_pvpCheck.sqf', file_path='functions/pvp/fn_pvpCheck.sqf', class_name='pvpCheck', function_name='A3A_fnc_pvpCheck')]}


@pytest.fixture()
def written_functions_hpp():
    return readit(pathmaker(THIS_FILE_DIR, '../functions.hpp'))
